events {}

http {
    upstream load_balancers {
        server lb-1:8080;
        server lb-2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://load_balancers;
            proxy_set_header X-Client-Id $http_x_client_id;
            proxy_set_header Host $host;
        }
    }
}
